### ISSUE TITLE
add a small testing hint to INSTALL

### ISSUE THREAD

**Issue by teuben** [danieljprice/giza#1]
the INSTALL file is great, but for the very impatient, how  can i quickly test getting a plot on the screen and a PS or PNG to see it's all working?  I would suggest to add a few lines to INSTALL on how to do this. There are some nice looking (make) fles in the test directory, but it didn't pass my threshold test to get it to do this kind of test.

**Comment by danieljprice** [comment]
Hi Peter,

 I've added a few hints to the INSTALL file, as suggested. The example dirs *were* simple but are made to look complicated by the automake stuff.

If you want to test a program that previously used PGPLOT, then (assuming a Mac with giza libraries installed to /usr/local/lib), just type:

export DYLD_LIBRARY_PATH=/usr/local/lib:${DYLD_LIBRARY_PATH}

then run your PGPLOT-based program (you don't even need to recompile it). That is, as long as giza's version of pgplot libraries are first in the shared library path, they are the ones that will be used.

If you want to use the giza API directly, check out the examples in the INSTALL file...

Hope that helps,

Daniel
