### ISSUE TITLE
pgqinf()

### ISSUE THREAD

**Issue by karlglazebrook** [danieljprice/giza#11]
pgqinf() is said to be implemented.

However none of the calls returns a value.

In particular: pgqinf("CURSOR",...) does not provide info on the interactivity of the device. This is used by the perl-pgplot test scripts test2.p and test9.p

**Comment by haavee** [comment]
Hi Karl,

The fix for this was merged quite recently: https://github.com/danieljprice/giza/pull/3#event-1937607620

The problem was that the FORTRAN `PGQINF()` was implemented but the C `cpgqinf()` wasn't. Now it is.

**Comment by karlglazebrook** [comment]
Confirming this now works.
