### ISSUE TITLE
giza-box-time still causes build failure on macports with v1.1.0

### ISSUE THREAD

**Issue by danieljprice** [danieljprice/giza#21]
we are still failing the macports build:

https://build.macports.org/builders/ports-10.6_i386_legacy-watcher/builds/20279
https://build.macports.org/builders/ports-10.6_x86_64_legacy-watcher/builds/20250
 https://build.macports.org/builders/ports-10.5_ppc_legacy-watcher/builds/19460

libtool: compile:  /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I.. -I/opt/local/include/cairo -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include/pixman-1 -I/opt/local/include/ossp -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include -pipe -Os -arch i386 -MT libgiza_la-giza-box-time.lo -MD -MP -MF .deps/libgiza_la-giza-box-time.Tpo -c giza-box-time.c  -fno-common -DPIC -o .libs/libgiza_la-giza-box-time.o
giza-box-time.c: In function ‘giza_box_time’:
giza-box-time.c:137: error: ‘for’ loop initial declaration used outside C99 mode
giza-box-time.c:139: error: ‘for’ loop initial declaration used outside C99 mode

**Comment by kencu** [comment]
If you're ever curious, I think you can duplicate the behaviour of gcc-4.2 by adding this to the Portfile (or the build):
```
configure.cflags-append -std=c89
```

**Comment by danieljprice** [comment]
Hello,

I am a master student in extragalactic astrophysics at the University of Oslo.

I am looking to use your SPLASH code in my masters project, to convert an SPH code over to a grid, in order to easier perform certain calculations on it.

However, I am having some installation trouble. I've followed the steps in your installation guide (Linux without admin permissions), and the first two steps run smoothly, but I am getting errors in the third step. The compiler is up to date and Cairo and X-Windows are installed.

The error message I get is pasted to the bottom of the mail (sorry if the formating is bad). It seems to be something wrong with giza_box_time. Do you have any idea how I could solve this? I could not find anything in the FAQs, and a local PhD student who is familiar with SPLASH had no clue.

Cheers,
Espen Hodne


Making install in src
make[3]: Entering directory `/mn/stornext/u3/espenhod/Documents/splash/giza/src'
  CC       libgiza_la-giza-annotate.lo
  CC       libgiza_la-giza-arrow-style.lo
  CC       libgiza_la-giza-arrow.lo
  CC       libgiza_la-giza-band-style.lo
  CC       libgiza_la-giza-band.lo
  CC       libgiza_la-giza-box-time.lo
giza-box-time.c: In function ‘giza_box_time’:
giza-box-time.c:137:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(char* px = xopt_cp; *px; px++ )
   ^
giza-box-time.c:137:3: note: use option -std=c99 or -std=gnu99 to compile your code
giza-box-time.c:139:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(char* py = yopt_cp; *py; py++ )
   ^
giza-box-time.c: In function ‘pgtbx1’:
giza-box-time.c:346:35: warning: unused variable ‘itick’ [-Wunused-variable]
     int               npl, ntick, itick;
                                   ^
giza-box-time.c: In function ‘pgtbx3’:
giza-box-time.c:571:36: warning: unused variable ‘rel_tick_sz’ [-Wunused-variable]
     double       lens, lenx, leny, rel_tick_sz;
                                    ^
giza-box-time.c: In function ‘pgtbx4’:
giza-box-time.c:693:13: warning: statement with no effect [-Wunused-value]
             it/*--*/;
             ^
giza-box-time.c:661:69: warning: unused variable ‘ylen2’ [-Wunused-variable]
     double       time, xlen, ylen, coord, fjust, rval, disp, xlen2, ylen2;
                                                                     ^
giza-box-time.c:661:62: warning: unused variable ‘xlen2’ [-Wunused-variable]
     double       time, xlen, ylen, coord, fjust, rval, disp, xlen2, ylen2;
                                                              ^
giza-box-time.c:661:30: warning: unused variable ‘ylen’ [-Wunused-variable]
     double       time, xlen, ylen, coord, fjust, rval, disp, xlen2, ylen2;
                              ^
giza-box-time.c:661:24: warning: unused variable ‘xlen’ [-Wunused-variable]
     double       time, xlen, ylen, coord, fjust, rval, disp, xlen2, ylen2;
                        ^
giza-box-time.c:659:18: warning: unused variable ‘asignl’ [-Wunused-variable]
     char         asignl;
                  ^
giza-box-time.c:656:18: warning: unused variable ‘f’ [-Wunused-variable]
     const int    f = 0;
                  ^
giza-box-time.c:655:18: warning: unused variable ‘t’ [-Wunused-variable]
     const int    t = 1;
                  ^
giza-box-time.c: In function ‘pgtbx5’:
giza-box-time.c:924:12: warning: unused variable ‘rem’ [-Wunused-variable]
     double rem, tmp;
            ^
giza-box-time.c:923:12: warning: unused variable ‘it’ [-Wunused-variable]
     int    it;
            ^
giza-box-time.c: In function ‘pgtbx7’:
giza-box-time.c:1064:5: warning: missing braces around initializer [-Wmissing-braces]
     char const* super[3][4] = { "\\ud\\d"       , "\\uh\\d"       , "\\um\\d"       , "\\us\\d",
     ^
giza-box-time.c:1064:5: warning: (near initialization for ‘super[0]’) [-Wmissing-braces]
make[3]: *** [libgiza_la-giza-box-time.lo] Error 1
make[3]: Leaving directory `/mn/stornext/u3/espenhod/Documents/splash/giza/src'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/mn/stornext/u3/espenhod/Documents/splash/giza'
make[1]: *** [../giza/lib/libgiza.a] Error 2
make[1]: Leaving directory `/mn/stornext/u3/espenhod/Documents/splash/build'
make: *** [withgiza] Error 2

**Comment by haavee** [comment]
The `giza-box-time()` function was only recently added and by the looks of it contains a small issue. I'll see if I can fix it right away.

Thanks for reporting this and apologies for the inconvenience.

**Comment by haavee** [comment]
Note: fixing the `unused variable` warnings is also somewhere on my todo list.

**Comment by danieljprice** [comment]
I’ve just fixed the unused variable warnings...

**Comment by danieljprice** [comment]
this should be fixed now
