### ISSUE TITLE
image transfer function

### ISSUE THREAD

**Issue by astronom57** [danieljprice/giza#27]
Hi there. Found a giza replacement for a conventional pgplot on my work desktop. Except for one case, everything seems to work. 

The case is: 
I am using a legacy script to plot images (VLBI source maps) using OOP version of pgplot from  PDL::Graphics::PGPLOT::Window like:

`$win->imag($im, {Justify => 1, ITF=>'log', RANGE=>[1e-3,max($im)], DrawWedge=>1});`

Apparently, with giza, it is unable to make a wedge in a log scale. Regardless of what is passed as ITF, the scale is linear. 
This is quite annoying for high signal-to-noise ratio images. Would be great if fixed.

**Comment by danieljprice** [comment]
yep, this is currently a "not implemented" for PGSITF and PGQITF, see status here: http://giza.sourceforge.net/documentation/pgplot.shtml

good news is it should be easy to do so, just nobody has ever requested this feature

**Comment by astronom57** [comment]
Good to hear. So please consider it as a feature request =)

**Comment by danieljprice** [comment]
This is now implemented and will be included in the next release
