### ISSUE TITLE
ft2build.h not found

### ISSUE THREAD

**Issue by jrthorstensen** [danieljprice/giza#33]
Hello --
I'm trying to build giza on a Fedora 29 system.  I found I needed cairo-devel, which installed smoothly with the dnf package manager used in recent fedoras.  However, the 'make install' fails: 
```
In file included from giza-set-font.c:40:
/usr/include/cairo/cairo-ft.h:46:10: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
          ^~~~~~~~~~~~
compilation terminated.
```
I apparently do have the freetype2 libraries installed;
```
[thorsten@minuet giza]$ pkg-config --cflags freetype2
-I/usr/include/freetype2 -I/usr/include/libpng16 
```
What''s the best way to fix this?

Thanks - John

**Comment by danieljprice** [comment]
hmm, they should be there most of the time. Can you confirm that ft2build.h exists in /usr/include  ?

The obvious thing to try is to (re)install freetype2 using your package manager, or like cairo there might be a developer package (freetype2-devel ?) that includes the needed header files.
