### ISSUE TITLE
marker issues

### ISSUE THREAD

**Issue by karlglazebrook** [danieljprice/giza#5]
Markers seem to be different from pgplot

e.g. test2.p in perl-pgplot

Marker 14 in pgpoint() should produce a 'plus' symbol, but instead produces a circle. Have not checked the rest.

Also the default marker size seems to be a lot smaller than in regular pgplot. It needs to be approximately doubled.

This may seem to be a minor point, but can make for a lot of regineering of plots.

**Comment by karlglazebrook** [comment]
Here is a comparison of markers in giza (top) vs pgplot (bottom)

https://www.dropbox.com/s/y8fz1me3nb5rgbh/gizavspgplot.png?dl=0

Marker 21 is one I use quite commonly and the change messes up a lot of plots - and ought to be easy to fix? The rest not so much, 19 seems very different

**Comment by haavee** [comment]
Busy going through these, so far four symbols done, stay tuned

**Comment by karlglazebrook** [comment]
This looks good with v1.1
