### ISSUE TITLE
Shared library libcpgplot.so no longer built

### ISSUE THREAD

**Issue by olebole** [danieljprice/giza#61]
When trying to update the Debian package to version 1.4.3, I miss the build of the libcpgplot shared library, which should be part of the Debian package. Is there a reason that this was removed, and can one re-enable it with `configure`? The static variant, `libcpgplot.a` is created.

**Comment by danieljprice** [comment]
thanks for reporting, this is likely a bug as I found the static libraries were not being built on Mac. Will fix!

**Comment by danieljprice** [comment]
now fixed on master, will push version bump pending discussion on #60

**Comment by olebole** [comment]
Thank you! This patch works well for me.
